function [fitresult, gof] = createFit(horz_train_x, horz_train_y, horz_train_z)
%CREATEFIT(HORZ_TRAIN_X,HORZ_TRAIN_Y,HORZ_TRAIN_Z)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : horz_train_x
%      Y Input : horz_train_y
%      Z Output: horz_train_z
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 08-May-2017 00:32:46


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( horz_train_x, horz_train_y, horz_train_z );

% Set up fittype and options.
ft = 'linearinterp';

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, 'Normalize', 'on' );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'untitled fit 1', 'horz_train_z vs. horz_train_x, horz_train_y', 'Location', 'NorthEast' );
% Label axes
xlabel horz_train_x
ylabel horz_train_y
zlabel horz_train_z
grid on
view( -9.0, 26.2 );


